package com.lithium.lexer;

public enum TokenType {
    // Keywords (existing)
    IF, ELSE, FOR, WHILE, IMPORT, EXPORT, SET, FUNCTION, RETURN, TEST,

    // Commands
    ASSERT_TEXT, ASSERT_VISIBLE, ASSERT_URL,
    CLICK, TYPE, CLEAR, DOUBLE_CLICK, RIGHT_CLICK, HOVER,
    SELECT, OPEN, BACK, FORWARD, REFRESH,
    SWITCH_TO_WINDOW, OPEN_TAB, CLOSE_TAB, LOG, WAIT,

    // Operators (expanded)
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    EQUALS, EQUALS_EQUALS, NOT_EQUALS,
    LESS_THAN, LESS_EQUALS, GREATER_THAN, GREATER_EQUALS,
    AND, OR, NOT,
    PLUS_EQUALS, MINUS_EQUALS, MULTIPLY_EQUALS, DIVIDE_EQUALS,
    INCREMENT, DECREMENT,

    // Symbols (existing)
    SEMICOLON, LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, DOT,

    // Others
    IDENTIFIER, STRING, NUMBER, COMMENT,

    // Special
    EOF
}
